### ISSUE TITLE
Issue with fs

### ISSUE THREAD

**Issue by michal-josef-spacek** [julianrojas87/ttl-merge#2]
When I installed ttl-merge, command is failing with:
```
> ttl-merge -i oai%3Aoai.bn.pt%3Abibliografianacional%2F1000159.ttl oai%3Aoai.bn.pt%3Abibliografianacional%2F1000717.ttl
/usr/local/lib/node_modules/ttl-merge/index.js:3
import fs from 'fs';
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

I was looking to package-lock.json and there is no fs module.
How could i fix this?

**Comment by julianrojas87** [comment]
Hi Michal,

Which version of Node.js are you using? (check with `node  -v` in the command line).
Judging by the error you are getting it seems you have a version that does not support ES6 modules.
Also, `fs` is a Node.js native library and for this reason it won't show as a dependency in package-lock.json

**Comment by michal-josef-spacek** [comment]
@julianrojas87 
```
woman:~> node -v
v10.24.0
```

**Comment by michal-josef-spacek** [comment]
Still is possible to install and same error.

**Comment by julianrojas87** [comment]
@michal-josef-spacek so your version of Node.js needs to be updated to v13 or higher to run this tool.

I also added the [engines](https://github.com/julianrojas87/ttl-merge/blob/72735e5c2c04fdf15bd97d5c94e504f261ec522a/package.json#L22) declaration and enable its strict mode to fail when attempting to install on older versions of Node.js.

Let me know if it works for you.

**Comment by michal-josef-spacek** [comment]
Still same (instalable, not working) on my version. (I understand, that i need v13 and higher)

**Comment by julianrojas87** [comment]
You are right is still possible to install, although a warning is shown:
![image](https://user-images.githubusercontent.com/4950659/155318891-28a926e1-dcb0-4b24-ba7a-d4f12182562c.png)

I will take a look at it. Were you able to run it in v13 or higher?

**Comment by michal-josef-spacek** [comment]
@julianrojas87 Probably issue with npm
```
woman:~# npm install -g ttl-merge
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/ttl-merge -> /usr/local/lib/node_modules/ttl-merge/index.js
+ ttl-merge@0.2.2
updated 1 package in 0.394s
```

Thanks for help, i will check on higher version.

**Comment by ThomasThelen** [comment]
FWIW I was able to install this and use it with the readme instructions with 
npm version: 9.8.0
node version: v20.5.0

```
thomas@Thomass-MacBook-Pro s2-coverings % npm install -g ttl-merge

added 14 packages in 4s

5 packages are looking for funding
  run `npm fund` for details
npm notice
npm notice New major version of npm available! 9.8.0 -> 11.0.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.0.0
npm notice Run npm install -g npm@11.0.0 to update!
npm notice
```

**Comment by julianrojas87** [comment]
Thanks for the report @ThomasThelen. I will then move on to closing this issue

**Comment by michal-josef-spacek** [comment]
I tested on my actual Debian:
```
woman:~> node -v
v18.19.0
woman:~> npm -v
9.2.0
woman:~> sudo npm install -g ttl-merge

added 7 packages, removed 2 packages, and changed 7 packages in 1s

5 packages are looking for funding
  run `npm fund` for details
```

Thanks.
